[project]
name = "cliclass"
description = "A library for generating CLI interfaces from dataclasses"
version = "0.1.0a1"
authors = [
	{name = "Andrej Kolčin", email = "self@kaathewise.net"}
]
license = "MPL-2.0"
requires-python = ">=3.14"
classifiers = [
	"Development Status :: 2 - Pre-Alpha",

	"Environment :: Console",
]

[project.optional-dependencies]
dev = [
    	"pytest~=9.0.3",
	"ty~=0.0.29",
	"ruff~=0.15.8",
]

[tool.ruff.lint]
select = ["E", "F", "I", "W", "RUF"]
ignore = ["E501", "F401"]

[tool.pytest]
testpaths = ["tests"]
python_files = ["*.py"]
strict_markers = true
